spring:
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:mysql://localhost:3306/reviewsmicroservice
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
#logging:
#  level:
#    org.springframework.web: DEBUG
server:
  port: 9001
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
      
Review Controller:
  getReviews: Get Reviews for a specific event.
